
### get all expenses
GET http://localhost:8080/expenses/all

### save expense
POST http://localhost:8080/expenses/add HTTP/1.1
Content-Type: application/json

{
  "description": "guitar",
  "amount": 20,
  "category": 1
}

### update expense
PUT http://localhost:8080/expenses/update/2 HTTP/1.1
Content-Type: application/json

{
  "description": "dinner",
  "amount": 31,
  "category": 1
}

### delete expense
DELETE http://localhost:8080/expenses/delete/1

### expense summary
GET http://localhost:8080/expenses/summary